version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Змінна середовища для підключення до бази даних.
      # Ім'я хоста 'db' відповідає назві сервісу PostgreSQL.
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://postgres:567234@db:5432/hw02
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

