services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - .:/app

  postgres_db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
